timekeeper/companies/urls.py
from django.urls import path 
from .import views 

#from django.conf.urls import url

app_name = 'companies'

urlpatterns = [
    # pages
    path('admin_company_list/', views.admin_company_list, name="admin_company_list"),
    #path(r'^admin_company_list_paginated/(?P<page>[0-9]+)/$', views.admin_company_list_paginated, name="admin_company_list_paginated"),
    #path('admin_company_list_paginated/<int>/', views.admin_company_list_paginated, name="admin_company_list_paginated"),
    #path(r'admin_company_list_paginated/(?P<page>\d+)/$', views.admin_company_list_paginated, name="admin_company_list_paginated"),
   
    path('admin_company_add/', views.admin_company_add, name="admin_company_add"),
    path('admin_company_add_error/', views.admin_company_add_error, name="admin_company_add_error"),

]

timekeeper/timekeeper/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('',include('tk_users.urls')),
    path(r'companies/',include('companies.urls')),
    path(r'admin/', admin.site.urls)
]

timekeeper/tk_users/urls.py
from django.contrib import admin
from django.urls import path 
from django.conf import settings
from django.conf.urls.static import static

from .import views 

app_name = 'tk_users'

urlpatterns = [
    # ex: /tk_users/
    path('',views.index, name="index"),
    
    path('general_user/', views.general_user, name="general_user"),
    path('general_user_upload_expenses/', views.general_user_upload_expenses, name="general_user_upload_expenses"),
    path('admin_user/', views.admin_user, name="admin_user"),
    path('admin_cognito_user_list/', views.admin_cognito_user_list, name="admin_cognito_user_list"),
    path('admin_cognito_user_add/', views.admin_cognito_user_add, name="admin_cognito_user_add"),
    #path('admin_cognito_user_error/', views.admin_cognito_user_error, name="admin_cognito_user_error"),
    #path('admin_cl/', views.admin_cognito_user_adding, name="admin_cognito_user_adding"),
    #path('admin_cognito_user_list_paginated/', views.admin_cognito_user_list_paginated, name="admin_cognito_user_list_paginated"),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

timekeeper/tk_users/models.py
from django.db import models

# Create your models here.

timekeeper/companies/forms.py
from django import forms

class AddCompanyForm(forms.Form):
    INDUSTRY_TYPE = (
        ('Hospitality','Hospitality'),
        ('Mining','Mining'),
        ('Healthcare','Healthcare'),
        ('Government','Government'),
        ('Waste','Waste'),
        ('IT','IT'),
        ('Music','Music'),
        ('Arts','Arts'),
        ('Culture','Culture'),
        ('Cinema','Cinema'),
        ('Entertainment','Entertainment'),
        ('Recreation','Recreation'),
        ('Utilities','Utilities'),
        ('Agriculture and Forestry','Agriculture and Forestry'),
        ('Construction','Construction'),
        ('Education','Education'),
        ('Transport','Transport'),
        ('Science','Science'),
        ('Pharma','Pharma'),
        ('Finance','Finance'),
        ('Retail','Retail'),
        ('Real Estate','Real Estate'),
        ('Sport','Sport'),
        ('Manufacturing','Manufacturing'),
        ('Engineering','Engineering'),
        ('Industrial','Industrial'),
        ('Landscaping','Landscaping'),
        ('Other','Other')
    )
    
    COUNTIES = (
        ('Antrim','Antrim'),
        ('Armagh','Armagh'),
        ('Cavan','Cavan'),
        ('Carlow','Carlow'),
        ('Clare','Clare'),
        ('Cork','Cork'),
        ('Derry','Derry'),
        ('Donegal','Donegal'),
        ('Down','Down'),
        ('Dublin','Dublin'),
        ('Fermanagh','Fermanagh'),
        ('Galway','Galway'),
        ('Kerry','Kerry'),
        ('Kildare','Kildare'),
        ('Kilkenny','Kilkenny'),
        ('Laois','Laois'),
        ('Leitrim','Leitrim'),
        ('Limerick','Limerick'),
        ('Longford','Longford'),
        ('Louth','Louth'),
        ('Mayo','Mayo'),
        ('Meath','Meath'),
        ('Monaghan','Monaghan'),
        ('Offaly','Offaly'),
        ('Roscommon','Roscommon'),
        ('Sligo','Sligo'),
        ('Tipperary','Tipperary'),
        ('Tyrone','Tyrone'),
        ('Waterford','Waterford'),
        ('Westmeath','Westmeath'),
        ('Wexford','Wexford'),
        ('Wicklow','Wicklow')
    )
    
    company_name = forms.CharField(
        label='Company Name ', 
        max_length=100,
        widget=forms.TextInput(attrs={'class':'form-control'})
    )
    county = forms.CharField(
        label = 'County ',
        widget = forms.Select(choices=COUNTIES, attrs={'class':'form-control'})
    )
    industry  = forms.CharField(
        label = 'Industry Type ',
        widget = forms.Select(choices=INDUSTRY_TYPE, attrs={'class':'form-control'})
    )

    lat = forms.CharField(
        label='Lat', 
        max_length=100,
        widget=forms.TextInput(attrs={'class':'form-control'})
    )
    lng = forms.CharField(
        label='Lng', 
        max_length=100,
        widget=forms.TextInput(attrs={'class':'form-control'})
    )
    
    '''
    eircode = forms.CharField(
        label='Eircode ', 
        max_length=20,
        widget=forms.TextInput(attrs={'class':'form-control'})
        
    )
    '''

timekeeper/tk_users/forms.py
from django import forms

class AddCognitoUserForm(forms.Form):
    email = forms.EmailField(label='email', max_length=100)
    password = forms.CharField(widget=forms.PasswordInput)
    

timekeeper/tk_users/views.py
from django.http import Http404
from django.urls import reverse
from django.shortcuts import render, redirect
from django.shortcuts import HttpResponse
from django.template.context_processors import csrf
from .forms import AddCognitoUserForm
from django.http import HttpResponseRedirect
from django.conf import settings
from django.shortcuts import redirect
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from botocore.exceptions import ClientError
from datetime import date
from django.conf import settings

import logging
import boto3 

#######################################################################
#   IMPORTING The Package that I have created and distributed to PyPi
#   https://pypi.org/project/upload-to-s3-folder-pkg/
#######################################################################

'''
from upload_to_s3_folder_pkg.upload_to_s3_folder import UploadToS3Folder
'''


############################################################################
# Welcome page for the application
############################################################################
def index(request):
    return render(request,'index.html')

############################################################################
#   GENERAL User Landing page
############################################################################
def general_user(request):
    args = {'heading' : 'General User Task'}
    return render(request,'general_user.html',args)

############################################################################    
#   UPLOAD EXPENSES RELATED TO SPECIFIC CLIENT
############################################################################
def general_user_upload_expenses(request):
    args = {'heading' : 'Upload Expenses'}
    dynamo_db_clients = list ()
    
    ######################################################
    #   Retrieve the list of clients from Dynamo DB
    ######################################################
    region = 'us-east-1'
   
    dynamo_client = DynamoDBDemo()
    table_name="timekeeper_client_list"
    client_list_resp = dynamo_client.get_items_A_to_Z(region, table_name)
    
    print('PRINTING THE RESPONSE FOR THE LIST')
    print(client_list_resp)
    
    # iterate over the returned client list and extract username and email and Status
    for client in client_list_resp:
        client_record = {
            #'eircode':client['eircode'],
            'company_name':client['company_name'],
            'industry': client['industry'],
            'county': client['county'],
            'lat': client['lat'],
            'lng': client['lng'],
        }
        
        dynamo_db_clients.append(client_record)
    
    args.update({'dynamo_db_clients':dynamo_db_clients})
    args.update({'message':''})
    
    #########################################################
    #   Check if the form was submitted
    #   If yes then upload the file locally first
    #   then to S3
    #########################################################
    if request.method == 'POST' and request.FILES['myfile']:

        company_name = request.POST['company_name']
        expense_type = request.POST['expense_type']

        myfile = request.FILES['myfile']
        fs = FileSystemStorage()
        
        try:
            
            #u = UploadToS3Folder()
            u = UploadToS3FolderClass()
            
            file_name_for_upload = u.generate_file_name(company_name,myfile)
            
            #   Save the file locally
            file_name = fs.save(file_name_for_upload, myfile)
            uploaded_file_url = fs.url(file_name)

            #########################################################
            #   UPLOAD the file to an S3 bucket
            #########################################################
            '''
            import os       #   package
            object_key = file_name
            save_path = settings.MEDIA_ROOT
            complete_name = os.path.join(save_path, object_key)
            
            print('\t Uploading to S3 Bucket from '+complete_name)
            '''
            # Upload the file to S3
            s3_client = boto3.client('s3')
            try:
                #bucket='timekeeperuploadbucket'  # bucket to load to
                bucket = settings.S3_BUCKET
                response = u.rename_and_upload_file_to_s3_folder(file_name,bucket,expense_type)
                
                
                '''
                #   expense type determines the S3 Bucket folder to ssave to
                if('travel'==expense_type):
                    response = s3_client.upload_file(complete_name, bucket, 'travel/{}'.format(file_name))
                elif('food'==expense_type):
                    response = s3_client.upload_file(complete_name, bucket, 'food/{}'.format(file_name))
                elif('accomodation'==expense_type):
                    response = s3_client.upload_file(complete_name, bucket, 'accomodation/{}'.format(file_name))
                elif('equipment'==expense_type):
                    response = s3_client.upload_file(complete_name, bucket, 'equipment/{}'.format(file_name))
                else: 
                    response = s3_client.upload_file(complete_name, bucket, object_key)
                '''
                
                print(response)
                args.update({'message':'**Upload Successful**'})
                
            except ClientError as e:
                logging.error(e)
                args.update({'message':'**Upload UnSuccessful**'})
                
        except ClientError as e:
            logging.error(e)
            args.update({'message':'**Upload UnSuccessful**'})


        return render(
            request, 
            'general_user_upload_expenses.html',
            args, 
            {'uploaded_file_url': uploaded_file_url}
        )
    else:
        return render(request, 'general_user_upload_expenses.html',args)   
 
    
############################################################################   
#   ADMIN User Landing page
############################################################################
def admin_user(request):
    args = {'heading' : 'Admin Task'}
    return render(request,'admin_user.html',args)
  
############################################################################ 
#   LISTING PAGE FOR COGNITO USERS
############################################################################
def admin_cognito_user_list(request):
    cognito_users = list ()
    user_id = 0
    
    # retrieve the list of users 
    region = 'us-east-1'
    UserPoolId='us-east-1_412rcjhr9'
    
    #   create a dictionary to pass all of the arguments
    args = {'region':region,'UserPoolId': UserPoolId}

    #   create an object of the Cognito class to do lookups of Cognito
    cognitoClient = Cognito()
    user_list_resp = cognitoClient.list_users(args)

    # iterate over the returned users and extract username and email and Status
    for user in user_list_resp['Users']:
        user_record = {'user_id': user_id, 'username': user['Username'], 'userstatus': user['UserStatus'], 'email': None}
        
        for attr in user['Attributes']:
            if attr['Name'] == 'email':
                user_record['email'] = attr['Value']
                
        cognito_users.append(user_record)
        user_id += 1
        
    #   pass the values to the template
    args = {'heading':'Cognito Users','cognito_users': cognito_users}
    return render(request,'cognito_user/admin_cognito_user_list.html',args)


############################################################################    
#   FUNCTION Creates A Cognito User based on values entered in a form  
############################################################################
def admin_cognito_user_add(request):
    
    #   Check if the request comes from the Congito Add User Form
    if request.method == 'POST':
        #   Create a form instance and populate it with the request data
        form = AddCognitoUserForm(request.POST)
        
        #  Check if the form contents is valid
        if form.is_valid():

            #   retrieve the data and
            #   Upload the new user to COGNITO using the Cognito Class functions
            email = request.POST['email']
            password = request.POST['password']
            region = 'us-east-1'
            cognitoClientID = '2neea3tmqro25ir2ohamglv1be'
            
            #   create a dictionary to pass all of the arguments
            args = {'email':email,'password': password,'region':region,'cognitoClientID':cognitoClientID}
        
            cognitoClient = Cognito()
            response = cognitoClient.sign_up_user(args)
            
            #   reload the UPDATED list of cognito users
            return redirect(reverse('tk_users:admin_cognito_user_list'))
    else:  
        form = AddCognitoUserForm()
        
        args = {'heading' : 'Add User', 'form': form}
        args.update(csrf(request))

        return render(request,'cognito_user/admin_cognito_user_add.html',args)


############################################################################
#   CLASSES SECTION
############################################################################ 

'''''''''''''''''''''''''''''''''''''''''''''''''''''''''
    S3 CLASS USED FOR INTERACTING WITH S3
    This will be replaced by PyPi package
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''

class UploadToS3FolderClass:
    
    #   generate a filename for upload specific to a client
    def generate_file_name(self,company_name,myfile):
        file_name = company_name.replace(" ", "_")+'__'+myfile.name.replace(" ", "_")
    
        return file_name

    #   retrieve the file from local upload and determine which folder it should be saved to
    def rename_and_upload_file_to_s3_folder(self, file_name, bucket, folder):
        #fs = FileSystemStorage()

timekeeper/tk_users/templates/admin_base.html
{% extends "base.html" %} 
{% block title %} Admin Page {% endblock %}
{% block content %}


<div class="container">
    <div>
      <h1 class="display-4"><a href="{% url 'tk_users:admin_user' %}">{{heading}}</a></h1>
    </div>
    &nbsp;
    <hr>
    {% block admin_content %}
    {% endblock %}
</div>

{% endblock %}

timekeeper/tk_users/templates/admin_cognito_user_add.html
{% extends "base.html" %} 
{% block title %} Home Page {% endblock %}
{% block content %}


<div class="container">
    <div>
      <h1 class="display-4">{{heading}}</h1>
    </div>
    <a href="{% url 'tk_users:admin_user' %}">Go Back</a> | <a href="{% url 'tk_users:admin_user' %}">Create User</a>
    <hr>
    <div id="COGNITO-data" class="card-deck row">
      ADD
    </div>
</div>

{% endblock %}

timekeeper/tk_users/templates/admin_user.html
{% extends "admin_base.html" %} 
{% load staticfiles %}
{% block scripts_top %}
  <link rel="stylesheet" href="{% static "css/admin/custom.css" %}">
{% endblock %}

{% block admin_content %}
<div class="list-group .centre">
  <a href="{% url 'tk_users:admin_cognito_user_list' %}" class="list-group-item list-group-item-action">Cognito Users <i class="fa fa-user-circle fa-align-center" aria-hidden="true"></i></a>
  <a href="{% url 'companies:admin_company_list' %}" class="list-group-item list-group-item-action">Clients <i class="fa fa-address-card fa-align-center" aria-hidden="true"></i></a>
</div>
{% endblock %}

timekeeper/tk_users/templates/general_base.html
{% extends "base.html" %} 
{% block title %} Time Keeper {% endblock %}
{% block content %}


<div class="container">
    <div>
      <h1 class="display-4"><a href="{% url 'tk_users:general_user' %}">{{heading}}</a></h1>
    </div>
    &nbsp;
    <hr>
    {% block general_content %}
    {% endblock %}
</div>

{% endblock %}

timekeeper/tk_users/templates/general_user.html
{% extends "base.html" %} 
{% load staticfiles %}
{% block scripts_top %}
  <link rel="stylesheet" href="{% static "css/admin/custom.css" %}">
{% endblock %}
{% block title %} General User Page {% endblock %}

{% block content %}
    <div class="container">
    <div>
      <h1 class="display-4"><a href="{% url 'tk_users:general_user' %}">{{heading}}</a></h1>
    </div>
    &nbsp;
    <hr>
    <div class="general_user_container">
        <div class="list-group .centre">
          <a href="{% url 'tk_users:general_user_upload_expenses' %}" class="list-group-item list-group-item-action">Upload Expenses &nbsp; <i class="fa fa-car fa-align-center" aria-hidden="true"></i> <i class="fa fa-subway fa-align-center" aria-hidden="true"></i> <i class="fa fa-plane fa-align-center" aria-hidden="true"></i> <i class="fa fa-cutlery" aria-hidden="true"></i></a>
        </div>
    </div>

{% endblock %}

timekeeper/tk_users/templates/general_user_upload_expenses.html
{% extends "base.html" %} 
{% load staticfiles %}
{% block scripts_top %}
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  		<script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
  		<link rel="stylesheet" href="{% static "css/maps/mapstyle.css" %}">
{% endblock %}


{% block title %} Home Page {% endblock %}

{% block content %}

    <div class="container">
    <div>
      <h1 class="display-4">{{heading}}</h1>
    </div>
    <a href="{% url 'tk_users:general_user' %}">Go Back</a>
    <hr>
    <div id="COGNITO-data" class="card-deck row">
      <div class="container">
        <div class="row">
          <div class="col-lg-6 col-md-6 col-xs-12 margin-top-1">
            <form method="POST" action="{% url 'tk_users:general_user_upload_expenses' %}" enctype="multipart/form-data" action>
              {% csrf_token %}
              <label for="company_name">Client: </label>
              <select id="company_name" name="company_name" class="form-control">
                  <option value="">--SELECT--</option> 
                {% for dynamo_db_client in dynamo_db_clients %}
                  <option value="{{dynamo_db_client.company_name}}__{{dynamo_db_client.county}}__{{dynamo_db_client.lat}}__{{dynamo_db_client.lng}}">{{dynamo_db_client.company_name}}</option>>
                {% endfor %}
              </select>
              <label for="expense_type">Expense Type: </label>
              <select id="expense_type" name="expense_type" class="form-control">
                <option value="travel">Travel</option>
                <option value="food">Food</option>
                <option value="accomodation">Accomodation</option>
                <option value="equipment">Equipment</option>
              </select>
              <label for="myfile">Receipts: </label>
              <input type="file" name="myfile" class="form-control">
              <label for="myfile">Latitude: </label>
              <input type="input" id="id_lat" name="id_lat" class="form-control" readonly>
              <label for="myfile">Longitude: </label>
              <input type="input" id="id_lng" name="id_lng" class="form-control" readonly>
              <hr>
              <div class="form-group">
                <button id="uploadbutton" type="submit" class="btn btn-orange btn-block">Upload</button>
              </div>
            </form>
          </div>
          <div class="col-lg-6 col-md-6 col-xs-12 margin-top-1">
            <p class="orange-text">{{message}}</p>
            <hr>
            <div id="map"></div>
          </div>
        </div>    
        {% if uploaded_file_url %}
          <p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
        {% endif %}
      </div>
    </div>

{% endblock %}
{% block scripts_bottom %}
    <script src="{% static "js/maps/map_constants.js" %}"></script>
    <script src="{% static "js/maps/map_load.js" %}"></script>
    <script src="{% static "js/maps/map_prepare_expenses.js" %}"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD0w1cO3ZEMdCW4n6GczBMRxiP92a7lhjA&callback=map_prepare_expenses&v=weekly" async></script>

{% endblock %}

timekeeper/tk_users/templates/index.html
{% extends "base.html" %} 
{% block title %} Home Page {% endblock %}
{% block content %}

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">TimeKeeper</h1>
    <p class="lead">Application for recording Employees and their Expenses against Client Projects</p>
  </div>
</div>
<div class="container">



{% endblock %}