timekeeper/companies/urls.py
from django.urls import path 
from .import views 

#from django.conf.urls import url

app_name = 'companies'

urlpatterns = [
    # pages
    path('admin_company_list/', views.admin_company_list, name="admin_company_list"),
    #path(r'^admin_company_list_paginated/(?P<page>[0-9]+)/$', views.admin_company_list_paginated, name="admin_company_list_paginated"),
    #path('admin_company_list_paginated/<int>/', views.admin_company_list_paginated, name="admin_company_list_paginated"),
    #path(r'admin_company_list_paginated/(?P<page>\d+)/$', views.admin_company_list_paginated, name="admin_company_list_paginated"),
   
    path('admin_company_add/', views.admin_company_add, name="admin_company_add"),
    path('admin_company_add_error/', views.admin_company_add_error, name="admin_company_add_error"),

]

timekeeper/timekeeper/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('',include('tk_users.urls')),
    path(r'companies/',include('companies.urls')),
    path(r'admin/', admin.site.urls)
]

timekeeper/tk_users/urls.py
from django.contrib import admin
from django.urls import path 
from django.conf import settings
from django.conf.urls.static import static

from .import views 

app_name = 'tk_users'

urlpatterns = [
    # ex: /tk_users/
    path('',views.index, name="index"),
    
    path('general_user/', views.general_user, name="general_user"),
    path('general_user_upload_expenses/', views.general_user_upload_expenses, name="general_user_upload_expenses"),
    path('admin_user/', views.admin_user, name="admin_user"),
    path('admin_cognito_user_list/', views.admin_cognito_user_list, name="admin_cognito_user_list"),
    path('admin_cognito_user_add/', views.admin_cognito_user_add, name="admin_cognito_user_add"),
    #path('admin_cognito_user_error/', views.admin_cognito_user_error, name="admin_cognito_user_error"),
    #path('admin_cl/', views.admin_cognito_user_adding, name="admin_cognito_user_adding"),
    #path('admin_cognito_user_list_paginated/', views.admin_cognito_user_list_paginated, name="admin_cognito_user_list_paginated"),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

timekeeper/companies/models.py
from django.db import models

# Create your models here.

class Company(models.Model):
    
    def __unicode__(self):
        return self.name
    
 
    INDUSTRY_TYPE = {
        ('Government','Government'),
        ('Transport','Transport'),
        ('IT','IT'),
        ('Retail','Retail'),
        ('Sport','Sport'),
        ('Hospitality','Hospitality'),
        ('IT','IT'),
        ('Agriculture','Agriculture'),
        ('Telecoms','Telecoms'),
        ('Food','Food'),
        ('Construction','Construction'),
        ('Farming','Farming'),
        ('Education','Education'),
        ('Pharma','Pharma'),
        ('Healthcare','Healthcare'),
        ('Entertainment','Entertainment'),
        ('Media','Media'),
        ('Energy','Energy'),
        ('Manufacturing','Manufacturing'),
        ('Music','Music'),
        ('Mining','Mining'),
        ('Electronics','Electronics')
    }
    
    COUNTIES = (
        ('Antrim', 'Antrim'),
        ('Armagh', 'Armagh'),
        ('Carlow', 'Carlow'),
        ('Cavan', 'Cavan'),
        ('Clare', 'Clare'),
        ('Cork', 'Cork'),
        ('Derry', 'Derry'),
        ('Donegal', 'Donegal'),
        ('Down', 'Down'),
        ('Dublin', 'Dublin'),
        ('Fermanagh', 'Fermanagh'),
        ('Galway', 'Galway'),
        ('Kerry', 'Kerry'),
        ('Kildare', 'Kildare'),
        ('Kilkenny', 'Kilkenny'),
        ('Laois', 'Laois'),
        ('Leitrim', 'Leitrim'),
        ('Limerick', 'Limerick'),
        ('Longford', 'Longford'),
        ('Louth', 'Louth'),
        ('Mayo', 'Mayo'),
        ('Meath', 'Meath'),
        ('Monaghan', 'Monaghan'),
        ('Offaly', 'Offaly'),
        ('Roscommon', 'Roscommon'),
        ('Sligo', 'Sligo'),
        ('Tipperary', 'Tipperary'),
        ('Tyrone', 'Tyrone'),
        ('Waterford', 'Waterford'),
        ('Westmeath', 'Westmeath'),
        ('Wexford', 'Wexford'),
        ('Wicklow', 'Wicklow'),
    )

    
    ############################################################################
    #   FIELDS
    ############################################################################
    name = models.CharField(
        max_length = 30
    )
    industry = models.CharField(
        max_length = 20,
        choices = INDUSTRY_TYPE,
        default = 'Government'
    )
    location = models.CharField(
        max_length = 15,
        choices = COUNTIES,
        default = 'Antrim'
    )
    

timekeeper/companies/forms.py
from django import forms

class AddCompanyForm(forms.Form):
    INDUSTRY_TYPE = (
        ('Hospitality','Hospitality'),
        ('Mining','Mining'),
        ('Healthcare','Healthcare'),
        ('Government','Government'),
        ('Waste','Waste'),
        ('IT','IT'),
        ('Music','Music'),
        ('Arts','Arts'),
        ('Culture','Culture'),
        ('Cinema','Cinema'),
        ('Entertainment','Entertainment'),
        ('Recreation','Recreation'),
        ('Utilities','Utilities'),
        ('Agriculture and Forestry','Agriculture and Forestry'),
        ('Construction','Construction'),
        ('Education','Education'),
        ('Transport','Transport'),
        ('Science','Science'),
        ('Pharma','Pharma'),
        ('Finance','Finance'),
        ('Retail','Retail'),
        ('Real Estate','Real Estate'),
        ('Sport','Sport'),
        ('Manufacturing','Manufacturing'),
        ('Engineering','Engineering'),
        ('Industrial','Industrial'),
        ('Landscaping','Landscaping'),
        ('Other','Other')
    )
    
    COUNTIES = (
        ('Antrim','Antrim'),
        ('Armagh','Armagh'),
        ('Cavan','Cavan'),
        ('Carlow','Carlow'),
        ('Clare','Clare'),
        ('Cork','Cork'),
        ('Derry','Derry'),
        ('Donegal','Donegal'),
        ('Down','Down'),
        ('Dublin','Dublin'),
        ('Fermanagh','Fermanagh'),
        ('Galway','Galway'),
        ('Kerry','Kerry'),
        ('Kildare','Kildare'),
        ('Kilkenny','Kilkenny'),
        ('Laois','Laois'),
        ('Leitrim','Leitrim'),
        ('Limerick','Limerick'),
        ('Longford','Longford'),
        ('Louth','Louth'),
        ('Mayo','Mayo'),
        ('Meath','Meath'),
        ('Monaghan','Monaghan'),
        ('Offaly','Offaly'),
        ('Roscommon','Roscommon'),
        ('Sligo','Sligo'),
        ('Tipperary','Tipperary'),
        ('Tyrone','Tyrone'),
        ('Waterford','Waterford'),
        ('Westmeath','Westmeath'),
        ('Wexford','Wexford'),
        ('Wicklow','Wicklow')
    )
    
    company_name = forms.CharField(
        label='Company Name ', 
        max_length=100,
        widget=forms.TextInput(attrs={'class':'form-control'})
    )
    county = forms.CharField(
        label = 'County ',
        widget = forms.Select(choices=COUNTIES, attrs={'class':'form-control'})
    )
    industry  = forms.CharField(
        label = 'Industry Type ',
        widget = forms.Select(choices=INDUSTRY_TYPE, attrs={'class':'form-control'})
    )

    lat = forms.CharField(
        label='Lat', 
        max_length=100,
        widget=forms.TextInput(attrs={'class':'form-control'})
    )
    lng = forms.CharField(
        label='Lng', 
        max_length=100,
        widget=forms.TextInput(attrs={'class':'form-control'})
    )
    
    '''
    eircode = forms.CharField(
        label='Eircode ', 
        max_length=20,
        widget=forms.TextInput(attrs={'class':'form-control'})
        
    )
    '''

timekeeper/companies/views.py
from django.urls import reverse
from django.shortcuts import render, redirect
from .forms import AddCompanyForm

import logging
import boto3
from botocore.exceptions import ClientError
from django.core.paginator import Paginator
from django.conf import settings

from pathlib import Path

path = Path(__file__).parent / "testfile.txt"


##################################################################################
#   List all of the Clients Stored on Dynamo DB Database
##################################################################################
def admin_company_list(request):
   
    region = 'us-east-1'
    table_name ="timekeeper_client_list"
    dynamo_db_clients = list ()
    
    #   create a dictionary to pass all of the arguments
    table_args = {'region':region,'table_name': table_name}
    
    dynamo_client = DynamoDB()
    client_list_resp = dynamo_client.get_items_A_to_Z(table_args)
    
    print('PRINTING THE RESPONSE FOR THE LIST')
    print(client_list_resp)
    
    #////////////////////////////////////////////////////
    #   for pagination
    #////////////////////////////////////////////////////
    p = Paginator(client_list_resp,settings.PAGE_SIZE)
    page_range = p.page_range
    
    # iterate over the returned client list and extract username and email and Status
    for client in client_list_resp:
        client_record = {
            #'eircode':client['eircode'],
            'company_name':client['company_name'],
            'industry': client['industry'],
            'county': client['county'],
            'lat': client['lat'],
            'lng': client['lng'],
        }
        dynamo_db_clients.append(client_record)
    
    args = {
        'heading':'Client Listing' ,
        'dynamo_db_clients':dynamo_db_clients,
        'page_range':page_range
    }
    return render(request,'companies/admin_company_list.html',args)


##################################################################################
#   List all of the Clients Stored on Dynamo DB Database
#   FOR TESTING
##################################################################################
'''
def admin_company_list_paginated(request):
   
   
    print(request)
   
    region = 'us-east-1'
    #table_name ="timekeeper_clients"
    table_name ="timekeeper_client_list"
    dynamo_db_clients = list ()
    
    
    #   create a dictionary to pass all of the arguments
    table_args = {'region':region,'table_name': table_name}
    
    dynamo_client = DynamoDB()
    
    #result = dynamo_client.dump_table(table_name,region)
    
    #print(result)
    
    
    client_list_resp = dynamo_client.get_items_A_to_Z(table_args)
    
    print(client_list_resp)
    
    
    p = Paginator(client_list_resp,settings.PAGE_SIZE)
    
    print('data passed to paginator')
    
    num_pages = p.count
    
    print("number of pages:")
    print(num_pages)
    
    page_range = p.page_range
    
    print("page range:")
    print(num_pages)
    
    page_number = p.page(1)
    
    print("page 1:")
    print(page_number)  
    
    page_data = page_number.object_list
    
    print("page_data:")
    print(page_data)  
    
    #print('PRINTING THE RESPONSE FOR THE LIST')
    #print(client_list_resp)
    
    # iterate over the returned client list and extract username and email and Status
    for client in page_data:
        client_record = {
            #'eircode':client['eircode'],
            'company_name':client['company_name'],
            'industry': client['industry'],
            'county': client['county'],
            'lat': client['lat'],
            'lng': client['lng'],
        }
        dynamo_db_clients.append(client_record)
    
    args = {
        'heading':'Client Listing' ,
        'dynamo_db_clients':dynamo_db_clients,
        'page_range':page_range
    }
    return render(request,'companies/admin_company_list.html',args)

'''


##################################################################################
#   Add a client to Dynamo DB
##################################################################################
def admin_company_add(request):
    region = 'us-east-1'
    table_name="timekeeper_client_list"
    
    #   CHECK IF THE FORM WAS SUBMITTED
    #   If so, then read in the contents of the form
    if request.method == 'POST':
        form = AddCompanyForm(request.POST)
        
        #   Check if the form contents is valid
        if form.is_valid():
            company_name = request.POST['company_name']
            industry  = request.POST['industry']
            #eircode  = request.POST['eircode']
            county = request.POST['county']
            lat = request.POST['lat']
            lng = request.POST['lng']
            
            item = {
                'company_name': company_name,
                'industry':industry,
                #'eircode': eircode,
                'county': county,
                'lat': lat,
                'lng': lng
            }
            print('form submitted')
            print(item)
            
            #   upload CLIENT to DYNAMO DB via use of a class
            dynamo_client = DynamoDB()
            
            #item = {
           #     "company_name": company_name,
           #     "industry" : industry,
           #     "eircode": eircode
           # }
            uploaded = dynamo_client.add_a_client(region, table_name, item)
            
            print('client was uploaded?')
            print(uploaded)
            
            #   CHECK if the UPLOAD WAS SUCCESSFUL
            #   If yes, diplay the list 
            #   If no, display error
            if uploaded:
                return redirect(reverse('companies:admin_company_list'))
            else:
                return redirect(reverse('companies:admin_company_add_error'))
                
            
    else:        
        
        #   If the page was just browsed to
        #   Then load an empty form
        form = AddCompanyForm()
    
        args = {'heading' : 'Add Client', 'form': form}
        return render(request,'companies/admin_company_add.html',args)

##################################################################################
#   Display ERROR Screen
##################################################################################
def admin_company_add_error(request):
    args = {'heading' : 'Upload Error'}
    return render(request,'companies/admin_company_add_error.html',args)      



##################################################################################
#    DYNAMO DB CLASS USED FOR INTERACTING WITH COGNITO
##################################################################################
class DynamoDB:
    
    
    #   CREATE A TABLE ON DYNAMO DB
    def create_table(self, table_name, key_schema, attribute_definitions, provisioned_throughput, region):
        
        try:
            dynamodb_resource = boto3.resource("dynamodb", region_name=region)
            self.table = dynamodb_resource.create_table(TableName=table_name, KeySchema=key_schema, AttributeDefinitions=attribute_definitions,
                ProvisionedThroughput=provisioned_throughput)

            # Wait until the table exists.
            self.table.meta.client.get_waiter('table_exists').wait(TableName=table_name)

        except ClientError as e:
            logging.error(e)
            return False
            
        return True
        
    #   UPLOAD AN ITEM TO THE SPECIFIED TABLE ON DYNAMO DB
    def add_a_client(self, region, table_name, item):
        try:
            dynamodb_resource = boto3.resource("dynamodb", region_name=region)
            table = dynamodb_resource.Table(table_name)
            table.put_item(Item=item)
        
        except ClientError as e:
            logging.error(e)
            return False
        return True
        
    #   RETRIEVE A SPECIFIED ITEM FROM A DYNAMO DB TABLE
    def get_an_item(self,region, table_name, key):
        try:
            dynamodb_resource = boto3.resource("dynamodb", region_name=region)
            table = dynamodb_resource.Table(table_name)
            response = table.get_item(Key=key)
            items_list = response['Item']
            
        except ClientError as e:
            logging.error(e)
            
        return(items_list)
        
    #   RETRIEVE A LIST OF ITEMS FROM A DYNAMO DB TABLE
    def get_items_A_to_Z(self,table_args):
        region = table_args['region']
        table_name = table_args['table_name']
        
        print('in get_items_A_to_Z')
        print('region is '+region)
        print('table name is '+table_name)

        
        
        try:
            dynamodb_resource = boto3.resource("dynamodb", region_name=region)
            table = dynamodb_resource.Table(table_name)
            
            response = table.scan(
                TableName=table_name,
                Select='ALL_ATTRIBUTES'
		    )
            return(response['Items'])
            
        except ClientError as e:
            logging.error(e)
            return([{'error': 'list empty'}])
        

timekeeper/companies/templates/companies/admin_company_add.bkp.html
{% extends "base.html" %} 
{% load staticfiles %}
{% block scripts_top %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
		<script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
		<link rel="stylesheet" href="{% static "css/companies/mapstyle.css" %}">
{% endblock %}
{% block title %} Add a Client {% endblock %}
{% load bootstrap_tags %}
{% block content %}


<div class="container">
    <div>
      <h1 class="display-4">{{heading}}</h1>
    </div>
    <a href="{% url 'tk_users:admin_user' %}">Go Back</a>
    <hr>
    <div id="COGNITO-data" class="card-deck row">
      <div class="container">
        <form id="clientForm" action="{% url 'companies:admin_company_add' %}" method="POST">
          {% csrf_token %}
          {{ form }}
          <hr>
          <div id="map"></div>
          Lat: <input type="text" id="lat" readonly>
		      Lng: <input type="text" id="lng" readonly>
		      <hr>

          <div class="form-group">
              <button type="submit" class="btn btn-orange btn-block">Create</button>
          </div>
        </form>
        <div id="map"></div>
      </div>
    </div>
</div>
{% endblock %}

{% block scripts_bottom %}
  <script src="{% static "js/companies/map_test.js" %}"></script>

  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD0w1cO3ZEMdCW4n6GczBMRxiP92a7lhjA&callback=initMap&v=weekly" async></script>
{% endblock %}
    

timekeeper/companies/templates/companies/admin_company_add.html
{% extends "base.html" %} 
{% load staticfiles %}
{% block scripts_top %}
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  		<script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
  		<link rel="stylesheet" href="{% static "css/maps/mapstyle.css" %}">
{% endblock %}
{% block title %} Add a Client {% endblock %}
{% load bootstrap_tags %}
{% block content %}

<div class="container">
    <div>
      <h1 class="display-4">{{heading}}</h1>
    </div>
    <a href="{% url 'tk_users:admin_user' %}">Go Back</a>
    <hr>
    <div id="COGNITO-data" class="card-deck row">
      <div class="container">
        <div class="row">
          <div class="col-lg-6 col-md-6 col-xs-12 margin-top-1">
            <form id="client_form" action="{% url 'companies:admin_company_add' %}" method="POST">
              {% csrf_token %}
              {{ form }}
              <hr>
              <div class="form-group">
                  <button type="submit" class="btn btn-orange btn-block">Create</button>
              </div>
            </form>
          </div>
          <div class="col-lg-6 col-md-6 col-xs-12 margin-top-1">
            <p>**Click on map or drag marker to Client Location</p>
            <hr>
            <div id="map"></div>
          </div>
        </div>
      </div>
    </div>
</div>
{% endblock %}

{% block scripts_bottom %}
    <script src="{% static "js/maps/map_constants.js" %}"></script>
    <script src="{% static "js/maps/map_load.js" %}"></script>
    <script src="{% static "js/maps/map_prepare_clients.js" %}"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD0w1cO3ZEMdCW4n6GczBMRxiP92a7lhjA&callback=map_prepare_clients&v=weekly" async></script>

{% endblock %}
    

timekeeper/companies/templates/companies/admin_company_add_error.html
{% extends "base.html" %} 
{% block title %} Home Page {% endblock %}
{% block content %}


<div class="container">
    <div>
      <h1 class="display-4">{{heading}}</h1>
    </div>
    <a href="{% url 'tk_users:admin_user' %}">Go Back</a> | <a href="{% url 'companies:admin_company_add' %}">Create Client</a>
    <hr>
    <div id="COGNITO-data" class="card-deck row">

      <p>An error Occurred in uploading to The Database. Please try again</p>

   </div>
  
  
</div>

{% endblock %}

timekeeper/companies/templates/companies/admin_company_base.html
{% extends "base.html" %} 
{% block title %} Admin Page {% endblock %}
{% block content %}


<div class="container">
    <div>
      <h1 class="display-4"><a href="{% url 'tk_users:admin_user' %}">{{heading}}</a></h1>
    </div>
    &nbsp;
    <hr>
    {% block admin_content %}
    {% endblock %}
</div>

{% endblock %}

timekeeper/companies/templates/companies/admin_company_list.html
{% extends "base.html" %} 
{% block title %} Home Page {% endblock %}
{% block content %}
<div class="container">
    <div>
      <h1 class="display-4">{{heading}}</h1>
    </div>
    <div class="container">
      <div clas="row">
        <div class="col-4 margin-top-1">
          <a href="{% url 'tk_users:admin_user' %}">Go Back</a> | <a href="{% url 'companies:admin_company_add' %}">Create Client</a>
        </div>  
        <hr>
        <div class="col-lg-6 col-md-6 col-xs-6 margin-top-1">Page: 
              {% for page in page_range %}
                <a href="{% url 'companies:admin_company_list' %}">{{page}}</a>
              {% endfor %}
        </div>
      </div>
    </div>
    <div id="COGNITO-data" class="card-deck row">
      {% for dynamo_db_client in dynamo_db_clients %}
          <div class="col-lg-3 col-md-6 col-xs-12 margin-top-1">
            <a href="">
              <div class="card h-100">
                <div class="card-header">
                  <i class="fa fa-address-card fa-5x fa-align-center" aria-hidden="true"></i>
                </div>
                <div class="card-body">
                  <h4 class="card-title">{{dynamo_db_client.company_name}}</h4>
                  <ul>
                    <li><span class="card_attr">COUNTY: </span>{{dynamo_db_client.county}}</li>
                    <li><span class="card_attr">INDUSTRY: </span>{{dynamo_db_client.industry}}</li>
                  </ul>
                </div>
              </div>
            </a>
          </div>  
      {% endfor %}
    </div>
</div>

{% endblock %}

timekeeper/companies/templates/companies/index.html
<p>Companies Index Page</p>